# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Nivriti/Desktop/University/Semester 4/Advanced logic design/risc-v_processor/risc-v_processor.srcs/sources_1/ip/data_memory/data_memory.xci
# IP: The module: 'data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nivriti/Desktop/University/Semester 4/Advanced logic design/risc-v_processor/risc-v_processor.gen/sources_1/ip/data_memory/data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Nivriti/Desktop/University/Semester 4/Advanced logic design/risc-v_processor/risc-v_processor.srcs/sources_1/ip/data_memory/data_memory.xci
# IP: The module: 'data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nivriti/Desktop/University/Semester 4/Advanced logic design/risc-v_processor/risc-v_processor.gen/sources_1/ip/data_memory/data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
