# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Nivriti/Downloads/Logic-design-project--main/Logic-design-project--main/Nexys4DDR_Master.xdc

# IP: ip/data_memory/data_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_memory || ORIG_REF_NAME==data_memory} -quiet] -quiet

# IP: ip/instruction_memory/instruction_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instruction_memory || ORIG_REF_NAME==instruction_memory} -quiet] -quiet
