# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nivriti/OneDrive/Desktop/University/Semester 4/Advanced logic design/advanced_logic_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nivriti/OneDrive/Desktop/University/Semester 4/Advanced logic design/advanced_logic_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Nivriti/OneDrive/Desktop/University/Semester 4/Advanced logic design/advanced_logic_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nivriti/OneDrive/Desktop/University/Semester 4/Advanced logic design/advanced_logic_project.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
